users: list = [
    {'Name': 'Dominik', 'posts': 1, 'city': 'Poznań'},
    {'Name': 'Patrycja', 'posts': 3, 'city': 'Warszawa'},
    {'Name': 'Szymon z wąsem', 'posts': 6, 'city': 'Inowrocław'},
    {'Name': 'Szymon', 'posts': 7, 'city': 'Białogard'},
    {'Name': 'Żerom', 'posts': 9, 'city': 'Tarnobrzeg'},
    {'Name': 'Michał', 'posts': 12, 'city': 'Kluczbork'},
    {'Name': 'Dominik', 'posts': 1000, 'city': 'Siedlce'},
    {'Name': 'Kinga', 'posts': 3, 'city': 'Gdynia'},
    {'Name': 'Amelia', 'posts': 11, 'city': 'Toruń'},
    {'Name': 'Julia', 'posts': 5, 'city': 'Zamość'},
    {'Name': 'Aleksandra', 'posts': 4, 'city': 'Radom'},
    {'Name': 'Patrycja', 'posts': 7, 'city': 'Mińsk Mazowiecki'},
    {'Name': 'Patrycja', 'posts': 15, 'city': 'Kraśnik'},
    {'Name': 'Patryk', 'posts': 20, 'city': 'Łódź'},
    {'Name': 'Karolina', 'posts': 15, 'city': 'Mława'},
]